# Custom enviroment variables

DOTDIR="$HOME/dotfiles"

# PATH
path+=("$HOME/.local/bin")
path+=("$HOME/.cargo/bin")
export PATH

# https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$XDG_STATE_HOME/zsh/history"
export HISTSIZE=1000
export SAVEHIST=1000
export TIMEFMT="REAL: %E\nCPU: %P"

# editing
export EDITOR="nvim"
export VISUAL="nvim"

# less
export LESSHISTFILE="$XDG_STATE_HOME/less/less.hist"

# X11
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"

# VSCode
export VSCODE_PORTABLE="$XDG_DATA_HOME/vscode"

# GNURadio
export GR_PREFS_PATH="$XDG_CONFIG_HOME/gnuradio"

# GDB
export GDBHISTFILE="$XDG_DATA_HOME/gdb/history"
